# tex - a tiny TeX engine
# (c) 2023 by Andreas Schwenk <mailto:contact@compiler-construction.com>
# License: GPL-3.0-or-later

name: tex_simple_example
description: Hello world example for the tex package
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  tex: ^0.5.2
