# tex - a tiny TeX engine
# (c) 2023 by Andreas Schwenk <mailto:contact@compiler-construction.com>
# License: GPL-3.0-or-later

name: tex
description: Tiny TeX to SVG engine by Andreas Schwenk. Glyphs are taken from MathJax.
version: 0.5.1
homepage: https://andreas-schwenk.github.io/tex/
repository: https://github.com/andreas-schwenk/tex

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1

screenshots:
  - description: 'This screenshot shows the output for "f(x)=x^2+y^2".'
    path: img/example.png
  