# tex - a tiny TeX engine
# (c) 2023-2024 by Andreas Schwenk <mailto:contact@compiler-construction.com>
# License: GPL-3.0-or-later

name: tex
description: Tiny TeX to SVG engine by Andreas Schwenk. Glyphs are taken from MathJax.
version: 1.0.2
homepage: https://andreas-schwenk.github.io/tex/
repository: https://github.com/andreas-schwenk/tex

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.7

screenshots:
  - description: 'Example rendering.'
    path: img/example2.png
