# tex - a tiny TeX engine
# (c) 2023-2024 by Andreas Schwenk <mailto:contact@compiler-construction.com>
# License: GPL-3.0-or-later

name: tex_web_example
description: Short web example to integrate TeX equations as inline math
version: 0.0.1

environment:
  sdk: ">=2.12.0 <4.0.0"

publish_to: none

dependencies:
  #tex: ^1.0.0
  tex:
    path: ../../
